version: '3'
services:
  api:
    container_name: app
    build:
      dockerfile: Dockerfile.local
      context: .
    ports:
    - "8080:8080"
    volumes:
      - ${PUT PATH TO PROJECT HERE}:/go/src/app