version: '3'
services:
  api:
    container_name: app
    build:
      dockerfile: Dockerfile.local
      context: .
    ports:
    - "8080:8080"
    volumes:
      - C:\Users\Mr.F\IdeaProjects\Twitter:/go/src/app